# clemenko
---
apiVersion: v1
kind: Namespace
metadata:
  name: xmrig
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xmrig
  namespace: xmrig
spec:
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
      - name: xmrig
        image: clemenko/xmrig
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
     #     privileged: true
        command: [ "/bin/sh", "-c", "/opt/xmrig*/xmrig -o \"rx.unmineable.com:3333\" -a \"rx/0\" -u \"SHIB:0xC08eccc4118c4176E706A6D6Ff53B4621b629B98.\"$(hostname)\"#rd17-hfyb\"" ]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
