jenkins:
  systemMessage: "Jenkins demo environment\n\n"
  numExecutors: 3
  scmCheckoutRetryCount: 2
  mode: NORMAL
  globalNodeProperties:
    - envVars:
        env:
          - key: ROX_API_TOKEN
            value: REPLACEME
          - key: ROX_URL
            value: https://central.stackrox
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "jenkins/slave"
              volumes:
                - hello:/hello
                - world:/world
              environmentsString: |
                hello=world
                foo=bar
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "10"
tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git
groovy:
  - script: >
      import jenkins.model.*;
      import hudson.security.*;
      import jenkins.security.s2m.AdminWhitelistRule;
      def instance = Jenkins.getInstance();
      def hudsonRealm = new HudsonPrivateSecurityRealm(false);
      hudsonRealm.createAccount("admin", "Pa22word");
      instance.setSecurityRealm(hudsonRealm);
      Jenkins.instance.getInjector().getInstance(AdminWhitelistRule.class).setMasterKillSwitch(false);
jobs:
  - script: >
      pipelineJob('StackRox_PluginSample') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                stages {
                  stage('Build') {
                    steps {
                      sh "mkdir \$BUILD_TAG"
                      sh "echo 'library/alpine' >> \$BUILD_TAG/rox_images_to_scan"
                      sh "echo 'clemenko/jenkins' >> \$BUILD_TAG/rox_images_to_scan"
                    }
                  }
                  stage('Push to Dev') {
                    steps {
                      sh "echo 'docker push library/alpine' "
                      sh "echo 'docker push clemenko/jenkins' "
                    }
                  }
                  stage('Stackrox Plugin Scan') {
                      steps {
                              step ([
                                \$class: 'StackroxBuilder', 
                                portalAddress: "\$ROX_URL",
                                apiToken: "\$ROX_API_TOKEN",
                                enableTLSVerification: false,
                                caCertPEM: '',
                                failOnCriticalPluginError: true,
                                failOnPolicyEvalFailure: true
                              ])
                      }
                  }
                  stage('Push to Prod') {
                    steps {
                      sh "echo 'docker push library/alpine' "
                      sh "echo 'docker push clemenko/jenkins' "
                    }
                  }
                }
              }""".stripIndent())
              sandbox()
          }
        }
      }